apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app

spec:
  replicas: 5

  selector:
    matchLabels:
      app: node-app

  template:
    metadata:
      labels:
        app: node-app

    spec:
      containers:
      - name: node-app
        image: baselmohsen/node-app:3c626def9fc2d0e1b8380f0f52fcb8a89f229eab
        ports:
        - containerPort: 3000